site_name: KaaS
site_description: Knowledge as a Service
site_author: Jimmy Briggs
site_url: https://kaas.jimbrig.com
copyright: Copyright &copy; 2021 Jimmy Briggs
repo_url: https://github.com/jimbrig/kaas
repo_name: jimbrig/KaaS
remote_branch: gh-pages
edit_uri: blob/main/docs/
use_directory_urls: true

theme:
  name: 'material'
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  - toc:
      permalink: true

plugins:
  - search
  - roamlinks 
